### ISSUE TITLE
[Question] Useable in middlewares?

### ISSUE THREAD

**Issue by Halfbax** [Blazored/LocalStorage#101]
Hello.

I would like to use this package in my middleware to grab some data. But you are using javascript injection and thats not allowed in the current state.

Do have any workaround, or do you recommend to use another package?

App: Blazor server

```


System.InvalidOperationException: JavaScript interop calls cannot be issued at this time. This is because the component is being statically rendered. When prerendering is enabled, JavaScript interop calls can only be performed during the OnAfterRenderAsync lifecycle method.

   at Microsoft.AspNetCore.Components.Server.Circuits.RemoteJSRuntime.BeginInvokeJS(Int64 asyncHandle, String identifier, String argsJson)

   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, CancellationToken cancellationToken, Object[] args)

   at Microsoft.JSInterop.JSRuntime.InvokeAsync[TValue](String identifier, Object[] args)

   at Blazored.LocalStorage.LocalStorageService.ContainKeyAsync(String key)

   at ProjectName.Core.Middlewares.AuthenticationMiddleware.InvokeAsync(HttpContext context, RequestDelegate next) in D:\projects\ProjectName\Core\Middlewares\AuthenticationMiddleware.cs:line 27

   at Microsoft.AspNetCore.Builder.UseMiddlewareExtensions.<>c__DisplayClass5_1.<<UseMiddlewareInterface>b__1>d.MoveNext()

--- End of stack trace from previous location ---

   at Microsoft.AspNetCore.Diagnostics.DeveloperExceptionPageMiddleware.Invoke(HttpContext context)


```

```cs
    public class AuthenticationMiddleware : IMiddleware
    {
        private ILocalStorageService _localStorage;
        private UserDataService _userDataService;
        private IUserService _userService;

        public AuthenticationMiddleware(ILocalStorageService localStorage, UserDataService userDataService, IUserService userService)
        {
            _localStorage = localStorage;
            _userDataService = userDataService;
            _userService = userService;
        }

        public async Task InvokeAsync(HttpContext context, RequestDelegate next)
        {

            if (await _localStorage.ContainKeyAsync("token"))
            {
                var token = await _localStorage.GetItemAsStringAsync("token");
                var user = await _userService.AuthenticateAsync(token);

                _userDataService.User = user.IsValid() ? user : null;
            }
            else
                _userDataService.User = null;

            await next(context);
        }
    }
```

**Comment by chrissainty** [comment]
Hi, local storage is only accessible with JavaScript, you can't use it from middleware. It's not a limitation of this package, what you're attempting just isn't possible.

**Comment by Halfbax** [comment]
Oh, thank you for the quick response. Thats sad. Any idea to bypass it?

**Comment by chrissainty** [comment]
You can't bypass it I'm afraid. At the point middleware is run you don't have access to the browser, and therefore, local storage.
