### ISSUE TITLE
[Bug] Event 111 is already tracked

### ISSUE THREAD

**Issue by hamdawg** [Blazored/LocalStorage#177]
**Describe the bug**
When I call the following code from a MudBlazor Button OnClick, if the local storage data isn't there, I get an error from blazor.webassembly.js

The reason I think it's the Blazored LocalStorage piece that is at fault is that I only get the error message when there isn't a value in local storage. It works fine if everything is in place. It also works fine if I skip the `LocalStorage.GetItemAsync` call and set `localHistory` to a `new Queue<Guid>()`.

**To Reproduce**
Call this code from a OnClick event with nothing in local storage 
```razor
@inject Blazored.LocalStorage.ILocalStorageService LocalStorage
@inject IDialogService DialogService

    <MudButton OnClick="_ => OpenRecentCases()">
        My Recent Cases
    </MudButton>

@code {
    private async void OpenRecentCases()
    {
        Queue<Guid> localHistory = await LocalStorage.GetItemAsync<Queue<Guid>>("recent.cases") ?? new Queue<Guid>();
        
        List<Case> recentCases = new List<Case>();
        if (localHistory.Any())
        {
            recentCases = await CaseRepository.CasesFromList(localHistory.ToList());
        }
        var dialogParams = new DialogParameters { { "RecentCases", recentCases } };
        DialogService.Show<RecentCasesDialog>("My Recent Cases", dialogParams, new DialogOptions { CloseButton = true });
    }
}
```

**Expected behavior**
Since this is valid code, it should not have errors.

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
WebAssembly

**Additional context**
Error from console:
```
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Event 111 is already tracked
      Error: Event 111 is already tracked
          at e.add (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:42463)
          at e.setListener (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:40697)
          at e.applyAttribute (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:36864)
          at e.insertElement (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:35698)
          at e.insertFrame (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:34569)
          at e.applyEdits (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:32955)
          at e.updateComponent (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:32271)
          at Object.t.renderBatch (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:12134)
          at Object.window.Blazor._internal.renderBatch (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:61913)
          at Object.w [as invokeJSFromDotNet] (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:64435)
Microsoft.JSInterop.JSException: Event 111 is already tracked
Error: Event 111 is already tracked
    at e.add (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:42463)
    at e.setListener (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:40697)
    at e.applyAttribute (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:36864)
    at e.insertElement (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:35698)
    at e.insertFrame (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:34569)
    at e.applyEdits (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:32955)
    at e.updateComponent (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:32271)
    at Object.t.renderBatch (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:12134)
    at Object.window.Blazor._internal.renderBatch (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:61913)
    at Object.w [as invokeJSFromDotNet] (http://localhost/actknowledge/v2/site/_framework/blazor.webassembly.js:1:64435)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object,Object](String identifier, Int32 arg0, RenderBatch arg1, Object arg2, Int64 targetInstanceId)
   at Microsoft.JSInterop.WebAssembly.WebAssemblyJSRuntime.InvokeUnmarshalled[Int32,RenderBatch,Object](String identifier, Int32 arg0, RenderBatch arg1)
   at Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer.UpdateDisplayAsync(RenderBatch& batch)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

**Comment by hamdawg** [comment]
Never mind. I was able to bypass your library with this code 
```c#
    private async Task OpenRecentCases()
    {
        string localHistory = await JSRuntime.InvokeAsync<string>("window.localStorage.getItem", "recent.cases") ?? "";
        localHistory = localHistory.Trim('[',']');
        
        List<Case> recentCases = new List<Case>();
        if (!string.IsNullOrEmpty(localHistory))
        { 
            List<Guid> guids = new List<Guid>();
            foreach (string str in ListDataMarshaller.Unmarshall(localHistory))
            {
                if (Guid.TryParse(str.Trim('"'), out var guid)) 
                    guids.Add(guid);
            }
            recentCases = await CaseRepository.CasesFromList(guids);
        }
        var dialogParams = new DialogParameters { { "RecentCases", recentCases } };
        DialogService.Show<RecentCasesDialog>("My Recent Cases", dialogParams, new DialogOptions { CloseButton = true });
   }
```
and I still got the same webassembly error, so it's not your library causing it. 
Sorry to bother you.
