### ISSUE TITLE
[Bug] Cannot use `LocalStorageOptions.JsonSerializerOptions.AddContext<TContext>()` when registering service

### ISSUE THREAD

**Issue by yueyinqiu** [Blazored/LocalStorage#200]
I'm trying [System.Text.Json source generation](https://learn.microsoft.com/en-us/dotnet/standard/serialization/system-text-json/source-generation) to avoid [trimming](https://learn.microsoft.com/en-us/dotnet/core/deploying/trimming/trim-self-contained) incompatibilities for a webassembly application.

So I created a serializer context, for example:

```csharp
    public class MyData
    {
        public string? Value1 { get; set; }
        public string? Value2 { get; set; }
    }

    [JsonSerializable(typeof(MyData))]
    public sealed partial class MyDataContext : JsonSerializerContext
    {
        // Codes will be generated by System.Text.Json source generation.
    }
```

And I have to find a place to use the context. I guess the best way is to do it like:

```csharp
_ = builder.Services.AddBlazoredLocalStorage((options) => {
    options.JsonSerializerOptions.AddContext<MyDataContext>();
});
```

However it failed. There is an exception thrown (service was injected into the index page):

```plain
crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: JsonSerializerOptions instances cannot be modified once encapsulated by a JsonSerializerContext. Such encapsulation can happen either when calling 'JsonSerializerOptions.AddContext' or when passing the options instance to a JsonSerializerContext constructor.
System.InvalidOperationException: JsonSerializerOptions instances cannot be modified once encapsulated by a JsonSerializerContext. Such encapsulation can happen either when calling 'JsonSerializerOptions.AddContext' or when passing the options instance to a JsonSerializerContext constructor.
   at System.Text.Json.ThrowHelper.ThrowInvalidOperationException_SerializerOptionsImmutable(JsonSerializerContext context)
   at System.Text.Json.JsonSerializerOptions.VerifyMutable()
   at System.Text.Json.JsonSerializerOptions.ConverterList.VerifyMutable()
   at System.Text.Json.Serialization.ConfigurationList`1[[System.Text.Json.Serialization.JsonConverter, System.Text.Json, Version=7.0.0.0, Culture=neutral, PublicKeyToken=cc7b13ffcd2ddd51]].Add(JsonConverter item)
   at Blazored.LocalStorage.ServiceCollectionExtensions.<>c__DisplayClass1_0.<AddBlazoredLocalStorage>b__0(LocalStorageOptions configureOptions)
   at Microsoft.Extensions.Options.ConfigureNamedOptions`1[[Blazored.LocalStorage.StorageOptions.LocalStorageOptions, Blazored.LocalStorage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3c577f5cf869402a]].Configure(String name, LocalStorageOptions options)
   at Microsoft.Extensions.Options.OptionsFactory`1[[Blazored.LocalStorage.StorageOptions.LocalStorageOptions, Blazored.LocalStorage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3c577f5cf869402a]].Create(String name)
   at Microsoft.Extensions.Options.UnnamedOptionsManager`1[[Blazored.LocalStorage.StorageOptions.LocalStorageOptions, Blazored.LocalStorage, Version=1.0.0.0, Culture=neutral, PublicKeyToken=3c577f5cf869402a]].get_Value()
   at Blazored.LocalStorage.Serialization.SystemTextJsonSerializer..ctor(IOptions`1 options)
   at System.Reflection.RuntimeConstructorInfo.Invoke(BindingFlags invokeAttr, Binder binder, Object[] parameters, CultureInfo culture)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitConstructor(ConstructorCallSite constructorCallSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSiteMain(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitCache(ServiceCallSite callSite, RuntimeResolverContext context, ServiceProviderEngineScope serviceProviderEngine, RuntimeResolverLock lockType)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.VisitScopeCache(ServiceCallSite callSite, RuntimeResolverContext context)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteVisitor`2[[Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeResolverContext, Microsoft.Extensions.DependencyInjection, Version=7.0.0.0, Culture=neutral, PublicKeyToken=adb9793829ddae60],[System.Object, System.Private.CoreLib, Version=7.0.0.0, Culture=neutral, PublicKeyToken=7cec85d7bea7798e]].VisitCallSite(ServiceCallSite callSite, RuntimeResolverContext argument)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.CallSiteRuntimeResolver.Resolve(ServiceCallSite callSite, ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.RuntimeServiceProviderEngine.<>c__DisplayClass4_0.<RealizeService>b__0(ServiceProviderEngineScope scope)
   at Microsoft.Extensions.DependencyInjection.ServiceProvider.GetService(Type serviceType, ServiceProviderEngineScope serviceProviderEngineScope)
   at Microsoft.Extensions.DependencyInjection.ServiceLookup.ServiceProviderEngineScope.GetService(Type serviceType)
   at Microsoft.AspNetCore.Components.ComponentFactory.<>c__DisplayClass7_0.<CreateInitializer>g__Initialize|1(IServiceProvider serviceProvider, IComponent component)
   at Microsoft.AspNetCore.Components.ComponentFactory.PerformPropertyInjection(IServiceProvider serviceProvider, IComponent instance)
   at Microsoft.AspNetCore.Components.ComponentFactory.InstantiateComponent(IServiceProvider serviceProvider, Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateComponent(Type componentType)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.InstantiateChildComponentOnFrame(RenderTreeFrame& frame, Int32 parentComponentId)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewComponentFrame(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InitializeNewSubtree(DiffContext& diffContext, Int32 frameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.InsertNewFrame(DiffContext& diffContext, Int32 newFrameIndex)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.AppendDiffEntriesForRange(DiffContext& diffContext, Int32 oldStartIndex, Int32 oldEndIndexExcl, Int32 newStartIndex, Int32 newEndIndexExcl)
   at Microsoft.AspNetCore.Components.RenderTree.RenderTreeDiffBuilder.ComputeDiff(Renderer renderer, RenderBatchBuilder batchBuilder, Int32 componentId, ArrayRange`1 oldTree, ArrayRange`1 newTree)
   at Microsoft.AspNetCore.Components.Rendering.ComponentState.RenderIntoBatch(RenderBatchBuilder batchBuilder, RenderFragment renderFragment, Exception& renderFragmentException)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.RenderInExistingBatch(RenderQueueEntry renderQueueEntry)
   at Microsoft.AspNetCore.Components.RenderTree.Renderer.ProcessRenderQueue()
```

Have I misused something, or it's a bug?

(I will later create a repo to put the some code for reproduce.)

**Comment by yueyinqiu** [comment]
The repo is created here: https://github.com/yueyinqiu/BlazoredLocalStorage.Issue200.git

**Comment by chrissainty** [comment]
So I'm not up to speed on the source generator stuff. But I've just had a quick google and found this issue: https://github.com/dotnet/runtime/issues/64025. It looks to describe the problem you're having and the reason why. Right now, I think the best way round this is to provide your own serialiser implementation and then you should have all the control you need. 

There is an example of apply a custom serialiser in the `samples/BlazorServer` folder. You would just need to make a cope of the https://github.com/Blazored/LocalStorage/blob/main/src/Blazored.LocalStorage/Serialization/SystemTextJsonSerializer.cs class and apply you're own customisations.

**Comment by yueyinqiu** [comment]
Replacing the serializer implementation could be a great idea. Thanks a lot.

**Comment by chrissainty** [comment]
I'm going to close this issue then as this seems to resolve the problem.
