### ISSUE TITLE
Error in .NET 8 : Method not found

### ISSUE THREAD

**Issue by segaranp** [Blazored/LocalStorage#233]
**Describe the bug**
Getting this error when calling SetItemAsync. Any reason why this is happening or how to prevent it?

blazor.web.js:1 crit: Microsoft.AspNetCore.Components.WebAssembly.Rendering.WebAssemblyRenderer[100]
      Unhandled exception rendering component: Method not found: System.Threading.Tasks.ValueTask Blazored.LocalStorage.ILocalStorageService.SetItemAsync<!0>(string,!!0,System.Threading.CancellationToken)
System.MissingMethodException: Method not found: System.Threading.Tasks.ValueTask Blazored.LocalStorage.ILocalStorageService.SetItemAsync<!0>(string,!!0,System.Threading.CancellationToken)
   at System.Runtime.CompilerServices.AsyncMethodBuilderCore.Start[<UserAuthenticated>d__19](<UserAuthenticated>d__19& stateMachine)
   at ProjectA.Web2.Client.Services.NewAuthenticationStateProvider.UserAuthenticated(ResponseUserLogin login, Boolean internalUser)
   at ProjectA.Web2.Client.Pages.LoginVM.Login() in C:\repo\ProjectA\ProjectA.Web2\ProjectA.Web2\ProjectA.Web2.Client\Pages\LoginVM.cs:line 26
   at ProjectA.Web2.Client.Login.OnLoginClick() in C:\repo\ProjectA\ProjectA.Web2\ProjectA.Web2\ProjectA.Web2.Client\Pages\Login.razor:line 87

**To Reproduce**

**Expected behavior**

**Screenshots**

**Hosting Model (is this issue happening with a certain hosting model?):**
 - Blazor Server
 - Blazor WebAssembly
 - etc...

**Additional context**

**Comment by binaryplates** [comment]
I'm facing the exact same error message in .NET 8 and Blazor WASM after updating my app to .NET 8.1.

**Comment by chrissainty** [comment]
I can't repro the issue and there isn't much to go on here. If you can provide more details I will take a further look. But I'm going to close this until then

**Comment by fr1g** [comment]
seems this is not able to be found if testing under a developing environment. but it is a problem if built into a production and deployed.
